---
title: "Portfolio1"
author: "Ryan Wheat"
date:
output: html_document
---

## Load packages and data

```{r load-packages}
library(tidyverse)
library(haven)
```

```{r load-data}
blood_pressure <- read_dta("25505-0011-Data.dta")
```


## Gender Breakdown

```{r histogram-bp}

#histogram of bp

ggplot(data = blood_pressure %>%
         filter(BPXDI1 > 0), 
       mapping = aes(x = BPXDI1)) + geom_histogram(color = "black", fill = "white" ) + labs(x = "Diastolic Blood Pressure")

```

```{r gender-histogram-bp}

#histogram of bp faceted by gender

ggplot(data = blood_pressure %>%
         filter(BPXDI1 > 0), 
       mapping = aes(x = BPXDI1)) + geom_histogram(color = "black", fill = "white") + facet_wrap(~ RIAGENDR) + labs(subtitle = "1 = Male, 2 = Female") + labs(x = "Diastolic Blood Pressure") + theme_dark()
```

```{r density-dist-gender}

#density distribution of bp, comparing genders

ggplot(data = blood_pressure %>%
         filter(BPXDI1 > 0), 
       mapping = aes(x = BPXDI1, color = as.factor(RIAGENDR))) + geom_density()

```

## Marital Status Breakdown

```{r marital-histogram-bp}

#histogram of marital status on bp

ggplot(data = blood_pressure %>%
         filter(BPXDI1 > 0),
       mapping = aes(x = BPXDI1, color = DMDMARTL)) + geom_histogram()


```


```{r marital-density-bp}

#density distribution of marital status on bp

ggplot(data = blood_pressure %>%
         filter(BPXDI1 > 0), 
       mapping = aes(x = BPXDI1)) + geom_density()
```
```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
